export const languages = [
  {
    labelCz: 'němčina',
    labelEn: 'German',
    labelDe: 'Deutsch',
    labelUa: 'німецька',
    color: '#F04627',
  },
  {
    labelCz: 'angličtina',
    labelEn: 'English',
    labelDe: 'Englisch',
    labelUa: 'англійська',
    color: '#FFC900',
  },
  {
    labelCz: 'čeština',
    labelEn: 'Czech',
    labelDe: 'Tschechisch',
    labelUa: 'чеська',
    color: '#9F6ACD',
  },
  {
    labelCz: 'japonština',
    labelEn: 'Japanese',
    labelDe: 'Japanisch',
    labelUa: '',
    color: '#FD828C',
  },
  {
    labelCz: 'italština',
    labelEn: 'Italian',
    labelDe: 'Italienisch',
    labelUa: 'італійська',
    color: '#00ABD3',
  },
  {
    labelCz: 'čínština',
    labelEn: 'Chinese',
    labelDe: 'Chinesisch',
    labelUa: 'китайська',
    color: '#FA881A',
  },
  {
    labelCz: 'španělština',
    labelEn: 'Spanish',
    labelDe: 'Spanisch',
    labelUa: 'іспанська',
    color: '#00AB3E',
  },
  {
    labelCz: 'francouzština',
    labelEn: 'French',
    labelDe: 'Französisch',
    labelUa: 'французька',
    color: '#FDBC60',
  },
  {
    labelCz: 'korejština',
    labelEn: 'Korean',
    labelDe: 'Koreanisch',
    labelUa: '',
    color: '#FDBC60',
  },
  {
    labelCz: 'indonéština',
    labelEn: 'Indonesian',
    labelDe: 'Indonesisch',
    labelUa: '',
    color: '#F04627',
  },
  {
    labelCz: 'švédština',
    labelEn: 'Swedish',
    labelDe: 'Schwedisch',
    labelUa: 'шведська',
    color: '#D9D9D9',
    disabled: true,
  },
  {
    labelCz: 'turečtina',
    labelEn: 'Turkish',
    labelDe: 'Türkisch',
    labelUa: 'турецька',
    color: '#D9D9D9',
    disabled: true,
  },
]
