export const links = [
  {
    labelCz: 'Aktuálně',
    labelEn: 'Currently',
    labelDe: 'Aktuell',
    labelUa: 'Течія',
    href: 'https://linktr.ee/rozmluv.se',
    external: true,
  },
  {
    labelCz: 'Reference',
    labelEn: 'References',
    labelDe: 'Referenzen',
    labelUa: 'довідка',
    href: '/#references',
  },
  {
    labelCz: 'Vyber jazyk',
    labelEn: 'Select language',
    labelDe: 'Sprache wählen',
    labelUa: 'вибір мови',
    href: '/#languages',
  },
  {
    labelCz: 'Ceník',
    labelEn: 'Pricelist',
    labelDe: 'Preisliste',
    labelUa: 'прайслист',
    href: '/#pricelist',
  },
  {
    labelCz: 'Zapoj firmu',
    labelEn: 'Involve your company',
    labelDe: 'Firma einbeziehen',
    labelUa: 'приєднати фірму',
    href: '/#companies',
  },
  {
    labelCz: 'Kontakt',
    labelEn: 'Contact',
    labelDe: 'Kontakt',
    labelUa: 'контакт',
    href: '/#contact',
  },
  {
    labelCz: 'O nás',
    labelEn: 'About us',
    labelDe: 'Über uns',
    labelUa: 'про нас',
    href: '/#about',
  },
]
