export const pricelist = [
  {
    labelCz: 'individuál',
    labelEn: 'individual',
    labelDe: 'einzeln',
    labelUa: 'індивідульне',
    peopleCz: '1 osoba',
    peopleEn: '1 person',
    peopleDe: 'je Person',
    peopleUa: 'за 1 особу',
    option1: '30 min. / 420 Kč',
    option2: '50 min. / 700 Kč',
    color: '#FFC900',
  },
  {
    labelCz: 'duál',
    labelEn: 'pair',
    labelDe: 'paarweise',
    labelUa: 'у парі',
    peopleCz: '2 osoby',
    peopleEn: '2 persons',
    peopleDe: '2 Personen',
    peopleUa: '',
    option1: '60 min. / 450 Kč',
    per1Cz: 'za 1 osobu',
    per1En: 'per 1 person',
    per1De: 'je Person',
    per1Ua: 'за 1 особу',
    color: '#9F6ACD',
  },
  {
    labelCz: 'skupina',
    labelEn: 'group',
    labelDe: 'als Gruppe',
    labelUa: 'групове',
    peopleCz: '3-5 osob',
    peopleEn: '3-5 persons',
    peopleDe: '3-5 Personen',
    peopleUa: '',
    option1: '60 min. / 330 Kč',
    per1Cz: 'za 1 osobu',
    per1En: 'per 1 person',
    per1De: 'je Person',
    per1Ua: '',
    option2: '90 min. / 495 kč',
    per2Cz: 'za 1 osobu',
    per2En: 'per 1 person',
    per2De: 'je Person',
    per2Ua: 'за 1 особу',
    color: '#FD828C',
  },
  {
    labelCz: 'dětská skupina',
    labelEn: "children's group",
    labelDe: 'Kindergruppe',
    labelUa: '',
    peopleCz: '7-10 osob',
    peopleEn: '7-10 persons',
    peopleDe: '7-10 Personen',
    peopleUa: '',
    option1: '60 min. / 190 Kč',
    per1Cz: 'za 1 osobu',
    per1En: 'per 1 person',
    per1De: 'je Person',
    per1Ua: 'за 1 особу',
    color: '#FA881A',
  },
]
